# Blueprint pour Render
# Ce fichier d√©finit l'infrastructure de l'application

databases:
  - name: blog-db
    plan: free
    databaseName: blog
    user: blog_user

services:
  - type: web
    name: blog-api
    runtime: python
    plan: free
    rootDir: back_dango
    buildCommand: "./build.sh"
    startCommand: "cd src && gunicorn blog.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.18"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: blog-db
          property: connectionString

staticSites:
  - name: blog-frontend
    rootDir: front_angular
    buildCommand: "npm install && npm run build"
    staticPublishPath: "dist/blog/browser"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
